var searchData=
[
  ['page_5fres',['PAGE_RES',['../a02647.html',1,'']]],
  ['page_5fres_5fit',['PAGE_RES_IT',['../a02663.html',1,'']]],
  ['pageiterator',['PageIterator',['../a02399.html',1,'tesseract']]],
  ['pangofontinfo',['PangoFontInfo',['../a04899.html',1,'tesseract']]],
  ['para',['PARA',['../a02635.html',1,'']]],
  ['paragraphmodel',['ParagraphModel',['../a02639.html',1,'']]],
  ['paragraphmodelsmearer',['ParagraphModelSmearer',['../a02443.html',1,'tesseract']]],
  ['paragraphtheory',['ParagraphTheory',['../a02439.html',1,'tesseract']]],
  ['parallel',['Parallel',['../a04595.html',1,'tesseract']]],
  ['param',['Param',['../a02903.html',1,'tesseract']]],
  ['param_5fdesc',['PARAM_DESC',['../a04283.html',1,'']]],
  ['paramcontent',['ParamContent',['../a02447.html',1,'']]],
  ['paramseditor',['ParamsEditor',['../a02451.html',1,'']]],
  ['paramsmodel',['ParamsModel',['../a05063.html',1,'tesseract']]],
  ['paramstrainingbundle',['ParamsTrainingBundle',['../a02671.html',1,'tesseract']]],
  ['paramstraininghypothesis',['ParamsTrainingHypothesis',['../a02667.html',1,'tesseract']]],
  ['paramsvectors',['ParamsVectors',['../a02895.html',1,'tesseract']]],
  ['paramutils',['ParamUtils',['../a02899.html',1,'tesseract']]],
  ['pb_5fline_5fit',['PB_LINE_IT',['../a02703.html',1,'']]],
  ['pdblk',['PDBLK',['../a02675.html',1,'']]],
  ['perm_5fconfig_5fstruct',['PERM_CONFIG_STRUCT',['../a04087.html',1,'']]],
  ['pgeventhandler',['PGEventHandler',['../a02459.html',1,'']]],
  ['pixelhistogram',['PixelHistogram',['../a04747.html',1,'tesseract']]],
  ['plumbing',['Plumbing',['../a04599.html',1,'tesseract']]],
  ['pointervector',['PointerVector',['../a02835.html',1,'tesseract']]],
  ['pointervector_3c_20genericvector_3c_20double_20_3e_20_3e',['PointerVector&lt; GenericVector&lt; double &gt; &gt;',['../a02835.html',1,'tesseract']]],
  ['pointervector_3c_20recodebeam_20_3e',['PointerVector&lt; RecodeBeam &gt;',['../a02835.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3abaselineblock_20_3e',['PointerVector&lt; tesseract::BaselineBlock &gt;',['../a02835.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3abaselinerow_20_3e',['PointerVector&lt; tesseract::BaselineRow &gt;',['../a02835.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3adocumentdata_20_3e',['PointerVector&lt; tesseract::DocumentData &gt;',['../a02835.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3aimagedata_20_3e',['PointerVector&lt; tesseract::ImageData &gt;',['../a02835.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3alanguagemodelstate_20_3e',['PointerVector&lt; tesseract::LanguageModelState &gt;',['../a02835.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3anetwork_20_3e',['PointerVector&lt; tesseract::Network &gt;',['../a02835.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3anetworkio_20_3e',['PointerVector&lt; tesseract::NetworkIO &gt;',['../a02835.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3ashape_20_3e',['PointerVector&lt; tesseract::Shape &gt;',['../a02835.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3atrainingsample_20_3e',['PointerVector&lt; tesseract::TrainingSample &gt;',['../a02835.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3atransposedarray_20_3e',['PointerVector&lt; tesseract::TransposedArray &gt;',['../a02835.html',1,'tesseract']]],
  ['pointervector_3c_20werd_5fres_20_3e',['PointerVector&lt; WERD_RES &gt;',['../a02835.html',1,'tesseract']]],
  ['poly_5fblock',['POLY_BLOCK',['../a02699.html',1,'']]],
  ['proto_5fkey',['PROTO_KEY',['../a04107.html',1,'']]],
  ['proto_5fset_5fstruct',['PROTO_SET_STRUCT',['../a04231.html',1,'']]],
  ['proto_5fstruct',['PROTO_STRUCT',['../a04299.html',1,'']]],
  ['prototype',['PROTOTYPE',['../a04147.html',1,'']]],
  ['ptrhash',['PtrHash',['../a04683.html',1,'tesseract']]]
];
