var searchData=
[
  ['page_5fres',['PAGE_RES',['../a02530.html',1,'']]],
  ['page_5fres_5fit',['PAGE_RES_IT',['../a02546.html',1,'']]],
  ['pageiterator',['PageIterator',['../a02278.html',1,'tesseract']]],
  ['pangofontinfo',['PangoFontInfo',['../a04722.html',1,'tesseract']]],
  ['para',['PARA',['../a02518.html',1,'']]],
  ['paragraphmodel',['ParagraphModel',['../a02522.html',1,'']]],
  ['paragraphmodelsmearer',['ParagraphModelSmearer',['../a02322.html',1,'tesseract']]],
  ['paragraphtheory',['ParagraphTheory',['../a02318.html',1,'tesseract']]],
  ['parallel',['Parallel',['../a04430.html',1,'tesseract']]],
  ['param',['Param',['../a02798.html',1,'tesseract']]],
  ['param_5fdesc',['PARAM_DESC',['../a04170.html',1,'']]],
  ['paramcontent',['ParamContent',['../a02326.html',1,'']]],
  ['paramseditor',['ParamsEditor',['../a02330.html',1,'']]],
  ['paramsmodel',['ParamsModel',['../a04854.html',1,'tesseract']]],
  ['paramstrainingbundle',['ParamsTrainingBundle',['../a02554.html',1,'tesseract']]],
  ['paramstraininghypothesis',['ParamsTrainingHypothesis',['../a02550.html',1,'tesseract']]],
  ['paramsvectors',['ParamsVectors',['../a02790.html',1,'tesseract']]],
  ['paramutils',['ParamUtils',['../a02794.html',1,'tesseract']]],
  ['pb_5fline_5fit',['PB_LINE_IT',['../a02586.html',1,'']]],
  ['pdblk',['PDBLK',['../a02558.html',1,'']]],
  ['perm_5fconfig_5fstruct',['PERM_CONFIG_STRUCT',['../a03974.html',1,'']]],
  ['pgeventhandler',['PGEventHandler',['../a02338.html',1,'']]],
  ['pixelhistogram',['PixelHistogram',['../a04582.html',1,'tesseract']]],
  ['plumbing',['Plumbing',['../a04434.html',1,'tesseract']]],
  ['pointervector',['PointerVector',['../a02730.html',1,'tesseract']]],
  ['pointervector_3c_20genericvector_3c_20double_20_3e_20_3e',['PointerVector&lt; GenericVector&lt; double &gt; &gt;',['../a02730.html',1,'tesseract']]],
  ['pointervector_3c_20recodebeam_20_3e',['PointerVector&lt; RecodeBeam &gt;',['../a02730.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3abaselineblock_20_3e',['PointerVector&lt; tesseract::BaselineBlock &gt;',['../a02730.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3abaselinerow_20_3e',['PointerVector&lt; tesseract::BaselineRow &gt;',['../a02730.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3adocumentdata_20_3e',['PointerVector&lt; tesseract::DocumentData &gt;',['../a02730.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3aimagedata_20_3e',['PointerVector&lt; tesseract::ImageData &gt;',['../a02730.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3alanguagemodelstate_20_3e',['PointerVector&lt; tesseract::LanguageModelState &gt;',['../a02730.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3anetwork_20_3e',['PointerVector&lt; tesseract::Network &gt;',['../a02730.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3anetworkio_20_3e',['PointerVector&lt; tesseract::NetworkIO &gt;',['../a02730.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3ashape_20_3e',['PointerVector&lt; tesseract::Shape &gt;',['../a02730.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3atrainingsample_20_3e',['PointerVector&lt; tesseract::TrainingSample &gt;',['../a02730.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3atransposedarray_20_3e',['PointerVector&lt; tesseract::TransposedArray &gt;',['../a02730.html',1,'tesseract']]],
  ['pointervector_3c_20werd_5fres_20_3e',['PointerVector&lt; WERD_RES &gt;',['../a02730.html',1,'tesseract']]],
  ['poly_5fblock',['POLY_BLOCK',['../a02582.html',1,'']]],
  ['proto_5fkey',['PROTO_KEY',['../a03994.html',1,'']]],
  ['proto_5fset_5fstruct',['PROTO_SET_STRUCT',['../a04118.html',1,'']]],
  ['proto_5fstruct',['PROTO_STRUCT',['../a04186.html',1,'']]],
  ['prototype',['PROTOTYPE',['../a04034.html',1,'']]],
  ['ptrhash',['PtrHash',['../a04518.html',1,'tesseract']]]
];
