var searchData=
[
  ['dangerr_5finfo',['DANGERR_INFO',['../a04298.html',1,'']]],
  ['dawg',['Dawg',['../a04258.html',1,'tesseract']]],
  ['dawgargs',['DawgArgs',['../a04286.html',1,'tesseract']]],
  ['dawgcache',['DawgCache',['../a04278.html',1,'tesseract']]],
  ['dawgloader',['DawgLoader',['../a04274.html',1,'tesseract']]],
  ['dawgposition',['DawgPosition',['../a04262.html',1,'tesseract']]],
  ['dawgpositionvector',['DawgPositionVector',['../a04266.html',1,'tesseract']]],
  ['debugpixa',['DebugPixa',['../a02430.html',1,'tesseract']]],
  ['denorm',['DENORM',['../a02510.html',1,'']]],
  ['detlinefit',['DetLineFit',['../a02434.html',1,'tesseract']]],
  ['dict',['Dict',['../a04290.html',1,'tesseract']]],
  ['dir128',['DIR128',['../a02506.html',1,'']]],
  ['docqualcallbacks',['DocQualCallbacks',['../a02242.html',1,'tesseract']]],
  ['documentcache',['DocumentCache',['../a02486.html',1,'tesseract']]],
  ['documentdata',['DocumentData',['../a02482.html',1,'tesseract']]],
  ['doubleparam',['DoubleParam',['../a02814.html',1,'tesseract']]],
  ['doubleptr',['DoublePtr',['../a02682.html',1,'tesseract']]],
  ['dppoint',['DPPoint',['../a02442.html',1,'tesseract']]]
];
