var searchData=
[
  ['dangerr_5finfo',['DANGERR_INFO',['../a04410.html',1,'']]],
  ['dawg',['Dawg',['../a04370.html',1,'tesseract']]],
  ['dawgargs',['DawgArgs',['../a04398.html',1,'tesseract']]],
  ['dawgcache',['DawgCache',['../a04390.html',1,'tesseract']]],
  ['dawgloader',['DawgLoader',['../a04386.html',1,'tesseract']]],
  ['dawgposition',['DawgPosition',['../a04374.html',1,'tesseract']]],
  ['dawgpositionvector',['DawgPositionVector',['../a04378.html',1,'tesseract']]],
  ['debugpixa',['DebugPixa',['../a02542.html',1,'tesseract']]],
  ['denorm',['DENORM',['../a02626.html',1,'']]],
  ['detlinefit',['DetLineFit',['../a02546.html',1,'tesseract']]],
  ['dict',['Dict',['../a04402.html',1,'tesseract']]],
  ['dir128',['DIR128',['../a02622.html',1,'']]],
  ['docqualcallbacks',['DocQualCallbacks',['../a02362.html',1,'tesseract']]],
  ['documentcache',['DocumentCache',['../a02598.html',1,'tesseract']]],
  ['documentdata',['DocumentData',['../a02594.html',1,'tesseract']]],
  ['doubleparam',['DoubleParam',['../a02918.html',1,'tesseract']]],
  ['doubleptr',['DoublePtr',['../a02798.html',1,'tesseract']]],
  ['dppoint',['DPPoint',['../a02554.html',1,'tesseract']]]
];
