var searchData=
[
  ['page_5fres',['PAGE_RES',['../a00501.html',1,'']]],
  ['page_5fres_5fit',['PAGE_RES_IT',['../a00502.html',1,'']]],
  ['pageiterator',['PageIterator',['../a00503.html',1,'tesseract']]],
  ['pairsizeinfo',['PairSizeInfo',['../a00504.html',1,'tesseract']]],
  ['pangofontinfo',['PangoFontInfo',['../a00505.html',1,'tesseract']]],
  ['para',['PARA',['../a00506.html',1,'']]],
  ['paragraphmodel',['ParagraphModel',['../a00507.html',1,'']]],
  ['paragraphmodelsmearer',['ParagraphModelSmearer',['../a00508.html',1,'tesseract']]],
  ['paragraphtheory',['ParagraphTheory',['../a00509.html',1,'tesseract']]],
  ['param',['Param',['../a00510.html',1,'tesseract']]],
  ['param_5fdesc',['PARAM_DESC',['../a00511.html',1,'']]],
  ['paramcontent',['ParamContent',['../a00512.html',1,'']]],
  ['paramseditor',['ParamsEditor',['../a00513.html',1,'']]],
  ['paramsmodel',['ParamsModel',['../a00514.html',1,'tesseract']]],
  ['paramstrainingbundle',['ParamsTrainingBundle',['../a00515.html',1,'tesseract']]],
  ['paramstraininghypothesis',['ParamsTrainingHypothesis',['../a00516.html',1,'tesseract']]],
  ['paramsvectors',['ParamsVectors',['../a00517.html',1,'tesseract']]],
  ['paramutils',['ParamUtils',['../a00518.html',1,'tesseract']]],
  ['pb_5fline_5fit',['PB_LINE_IT',['../a00519.html',1,'']]],
  ['pdblk',['PDBLK',['../a00520.html',1,'']]],
  ['perm_5fconfig_5fstruct',['PERM_CONFIG_STRUCT',['../a00521.html',1,'']]],
  ['pgeventhandler',['PGEventHandler',['../a00522.html',1,'']]],
  ['pixelhistogram',['PixelHistogram',['../a00523.html',1,'tesseract']]],
  ['pointervector',['PointerVector',['../a00524.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3abaselineblock_20_3e',['PointerVector&lt; tesseract::BaselineBlock &gt;',['../a00524.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3abaselinerow_20_3e',['PointerVector&lt; tesseract::BaselineRow &gt;',['../a00524.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3adocumentdata_20_3e',['PointerVector&lt; tesseract::DocumentData &gt;',['../a00524.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3aimagedata_20_3e',['PointerVector&lt; tesseract::ImageData &gt;',['../a00524.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3alanguagemodelstate_20_3e',['PointerVector&lt; tesseract::LanguageModelState &gt;',['../a00524.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3ashape_20_3e',['PointerVector&lt; tesseract::Shape &gt;',['../a00524.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3atrainingsample_20_3e',['PointerVector&lt; tesseract::TrainingSample &gt;',['../a00524.html',1,'tesseract']]],
  ['pointervector_3c_20werd_5fres_20_3e',['PointerVector&lt; WERD_RES &gt;',['../a00524.html',1,'tesseract']]],
  ['poly_5fblock',['POLY_BLOCK',['../a00525.html',1,'']]],
  ['post_5ftable',['post_table',['../a00526.html',1,'']]],
  ['proto_5fkey',['PROTO_KEY',['../a00527.html',1,'']]],
  ['proto_5fset_5fstruct',['PROTO_SET_STRUCT',['../a00528.html',1,'']]],
  ['proto_5fstruct',['PROTO_STRUCT',['../a00529.html',1,'']]],
  ['prototype',['PROTOTYPE',['../a00530.html',1,'']]],
  ['ptrhash',['PtrHash',['../a00531.html',1,'tesseract']]]
];
