var searchData=
[
  ['dangerr_5finfo',['DANGERR_INFO',['../a00345.html',1,'']]],
  ['dawg',['Dawg',['../a00346.html',1,'tesseract']]],
  ['dawgargs',['DawgArgs',['../a00347.html',1,'tesseract']]],
  ['dawgcache',['DawgCache',['../a00348.html',1,'tesseract']]],
  ['dawgloader',['DawgLoader',['../a00349.html',1,'tesseract']]],
  ['dawgposition',['DawgPosition',['../a00350.html',1,'tesseract']]],
  ['dawgpositionvector',['DawgPositionVector',['../a00351.html',1,'tesseract']]],
  ['denorm',['DENORM',['../a00352.html',1,'']]],
  ['detlinefit',['DetLineFit',['../a00353.html',1,'tesseract']]],
  ['dict',['Dict',['../a00354.html',1,'tesseract']]],
  ['dir128',['DIR128',['../a00355.html',1,'']]],
  ['docqualcallbacks',['DocQualCallbacks',['../a00356.html',1,'tesseract']]],
  ['documentcache',['DocumentCache',['../a00357.html',1,'tesseract']]],
  ['documentdata',['DocumentData',['../a00358.html',1,'tesseract']]],
  ['doubleparam',['DoubleParam',['../a00359.html',1,'tesseract']]],
  ['doubleptr',['DoublePtr',['../a00360.html',1,'tesseract']]],
  ['dppoint',['DPPoint',['../a00361.html',1,'tesseract']]]
];
