var searchData=
[
  ['page_5fres',['PAGE_RES',['../a00485.html',1,'']]],
  ['page_5fres_5fit',['PAGE_RES_IT',['../a00486.html',1,'']]],
  ['pageiterator',['PageIterator',['../a00487.html',1,'tesseract']]],
  ['pairsizeinfo',['PairSizeInfo',['../a00488.html',1,'tesseract']]],
  ['pangofontinfo',['PangoFontInfo',['../a00489.html',1,'tesseract']]],
  ['para',['PARA',['../a00490.html',1,'']]],
  ['paragraphmodel',['ParagraphModel',['../a00491.html',1,'']]],
  ['paragraphmodelsmearer',['ParagraphModelSmearer',['../a00492.html',1,'tesseract']]],
  ['paragraphtheory',['ParagraphTheory',['../a00493.html',1,'tesseract']]],
  ['param',['Param',['../a00494.html',1,'tesseract']]],
  ['param_5fdesc',['PARAM_DESC',['../a00495.html',1,'']]],
  ['paramcontent',['ParamContent',['../a00496.html',1,'']]],
  ['paramseditor',['ParamsEditor',['../a00497.html',1,'']]],
  ['paramsmodel',['ParamsModel',['../a00498.html',1,'tesseract']]],
  ['paramstrainingbundle',['ParamsTrainingBundle',['../a00499.html',1,'tesseract']]],
  ['paramstraininghypothesis',['ParamsTrainingHypothesis',['../a00500.html',1,'tesseract']]],
  ['paramsvectors',['ParamsVectors',['../a00501.html',1,'tesseract']]],
  ['paramutils',['ParamUtils',['../a00502.html',1,'tesseract']]],
  ['pb_5fline_5fit',['PB_LINE_IT',['../a00503.html',1,'']]],
  ['pdblk',['PDBLK',['../a00504.html',1,'']]],
  ['perm_5fconfig_5fstruct',['PERM_CONFIG_STRUCT',['../a00505.html',1,'']]],
  ['pgeventhandler',['PGEventHandler',['../a00506.html',1,'']]],
  ['pixelhistogram',['PixelHistogram',['../a00507.html',1,'tesseract']]],
  ['pointervector',['PointerVector',['../a00508.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3abaselineblock_20_3e',['PointerVector&lt; tesseract::BaselineBlock &gt;',['../a00508.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3abaselinerow_20_3e',['PointerVector&lt; tesseract::BaselineRow &gt;',['../a00508.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3adocumentdata_20_3e',['PointerVector&lt; tesseract::DocumentData &gt;',['../a00508.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3aimagedata_20_3e',['PointerVector&lt; tesseract::ImageData &gt;',['../a00508.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3alanguagemodelstate_20_3e',['PointerVector&lt; tesseract::LanguageModelState &gt;',['../a00508.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3ashape_20_3e',['PointerVector&lt; tesseract::Shape &gt;',['../a00508.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3atrainingsample_20_3e',['PointerVector&lt; tesseract::TrainingSample &gt;',['../a00508.html',1,'tesseract']]],
  ['pointervector_3c_20werd_5fres_20_3e',['PointerVector&lt; WERD_RES &gt;',['../a00508.html',1,'tesseract']]],
  ['poly_5fblock',['POLY_BLOCK',['../a00509.html',1,'']]],
  ['proto_5fkey',['PROTO_KEY',['../a00510.html',1,'']]],
  ['proto_5fset_5fstruct',['PROTO_SET_STRUCT',['../a00511.html',1,'']]],
  ['proto_5fstruct',['PROTO_STRUCT',['../a00512.html',1,'']]],
  ['prototype',['PROTOTYPE',['../a00513.html',1,'']]],
  ['ptrhash',['PtrHash',['../a00514.html',1,'tesseract']]]
];
