var searchData=
[
  ['dangerr_5finfo',['DANGERR_INFO',['../a04565.html',1,'']]],
  ['dawg',['Dawg',['../a04525.html',1,'tesseract']]],
  ['dawgargs',['DawgArgs',['../a04553.html',1,'tesseract']]],
  ['dawgcache',['DawgCache',['../a04545.html',1,'tesseract']]],
  ['dawgloader',['DawgLoader',['../a04541.html',1,'tesseract']]],
  ['dawgposition',['DawgPosition',['../a04529.html',1,'tesseract']]],
  ['dawgpositionvector',['DawgPositionVector',['../a04533.html',1,'tesseract']]],
  ['denorm',['DENORM',['../a02613.html',1,'']]],
  ['detlinefit',['DetLineFit',['../a02533.html',1,'tesseract']]],
  ['dict',['Dict',['../a04557.html',1,'tesseract']]],
  ['dir128',['DIR128',['../a02609.html',1,'']]],
  ['docqualcallbacks',['DocQualCallbacks',['../a02349.html',1,'tesseract']]],
  ['documentcache',['DocumentCache',['../a02585.html',1,'tesseract']]],
  ['documentdata',['DocumentData',['../a02581.html',1,'tesseract']]],
  ['doubleparam',['DoubleParam',['../a02909.html',1,'tesseract']]],
  ['doubleptr',['DoublePtr',['../a02785.html',1,'tesseract']]],
  ['dppoint',['DPPoint',['../a02541.html',1,'tesseract']]]
];
