var searchData=
[
  ['page_5fres',['PAGE_RES',['../a02633.html',1,'']]],
  ['page_5fres_5fit',['PAGE_RES_IT',['../a02649.html',1,'']]],
  ['pageiterator',['PageIterator',['../a02385.html',1,'tesseract']]],
  ['pairsizeinfo',['PairSizeInfo',['../a04497.html',1,'tesseract']]],
  ['pangofontinfo',['PangoFontInfo',['../a04897.html',1,'tesseract']]],
  ['para',['PARA',['../a02621.html',1,'']]],
  ['paragraphmodel',['ParagraphModel',['../a02625.html',1,'']]],
  ['paragraphmodelsmearer',['ParagraphModelSmearer',['../a02429.html',1,'tesseract']]],
  ['paragraphtheory',['ParagraphTheory',['../a02425.html',1,'tesseract']]],
  ['param',['Param',['../a02893.html',1,'tesseract']]],
  ['param_5fdesc',['PARAM_DESC',['../a04261.html',1,'']]],
  ['paramcontent',['ParamContent',['../a02433.html',1,'']]],
  ['paramseditor',['ParamsEditor',['../a02437.html',1,'']]],
  ['paramsmodel',['ParamsModel',['../a05005.html',1,'tesseract']]],
  ['paramstrainingbundle',['ParamsTrainingBundle',['../a02657.html',1,'tesseract']]],
  ['paramstraininghypothesis',['ParamsTrainingHypothesis',['../a02653.html',1,'tesseract']]],
  ['paramsvectors',['ParamsVectors',['../a02885.html',1,'tesseract']]],
  ['paramutils',['ParamUtils',['../a02889.html',1,'tesseract']]],
  ['pb_5fline_5fit',['PB_LINE_IT',['../a02689.html',1,'']]],
  ['pdblk',['PDBLK',['../a02661.html',1,'']]],
  ['perm_5fconfig_5fstruct',['PERM_CONFIG_STRUCT',['../a04065.html',1,'']]],
  ['pgeventhandler',['PGEventHandler',['../a02445.html',1,'']]],
  ['pixelhistogram',['PixelHistogram',['../a04749.html',1,'tesseract']]],
  ['pointervector',['PointerVector',['../a02821.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3abaselineblock_20_3e',['PointerVector&lt; tesseract::BaselineBlock &gt;',['../a02821.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3abaselinerow_20_3e',['PointerVector&lt; tesseract::BaselineRow &gt;',['../a02821.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3adocumentdata_20_3e',['PointerVector&lt; tesseract::DocumentData &gt;',['../a02821.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3aimagedata_20_3e',['PointerVector&lt; tesseract::ImageData &gt;',['../a02821.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3alanguagemodelstate_20_3e',['PointerVector&lt; tesseract::LanguageModelState &gt;',['../a02821.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3ashape_20_3e',['PointerVector&lt; tesseract::Shape &gt;',['../a02821.html',1,'tesseract']]],
  ['pointervector_3c_20tesseract_3a_3atrainingsample_20_3e',['PointerVector&lt; tesseract::TrainingSample &gt;',['../a02821.html',1,'tesseract']]],
  ['pointervector_3c_20werd_5fres_20_3e',['PointerVector&lt; WERD_RES &gt;',['../a02821.html',1,'tesseract']]],
  ['poly_5fblock',['POLY_BLOCK',['../a02685.html',1,'']]],
  ['proto_5fkey',['PROTO_KEY',['../a04085.html',1,'']]],
  ['proto_5fset_5fstruct',['PROTO_SET_STRUCT',['../a04209.html',1,'']]],
  ['proto_5fstruct',['PROTO_STRUCT',['../a04277.html',1,'']]],
  ['prototype',['PROTOTYPE',['../a04125.html',1,'']]],
  ['ptrhash',['PtrHash',['../a04685.html',1,'tesseract']]]
];
